export type Locale = "zh-CN" | "en";
export type Localized = {"zh-CN":string;en:string};
export type Chapter = {kicker:Localized;title:Localized;line:Localized;formula:string;note:Localized;evidence:"PAPER"|"REAL SAMPLE"|"CHECKPOINT"|"TEACHING"};

const z=(zh:string,en:string):Localized=>({"zh-CN":zh,en});

export const CHAPTERS:Chapter[]=[
  {kicker:z("为什么需要共同空间","A common spatial language"),title:z("为什么是 BEV","Why BEV"),line:z("六张透视图各自拥有不同的尺度、遮挡和坐标。LSS 把语义先 Lift 到潜在三维，再在 ego 坐标 Splat 成规则鸟瞰网格。","Six perspective views disagree about scale, occlusion and coordinates. LSS lifts semantics into latent 3D, then splats them into a regular ego-centric grid."),formula:"images → Lift → Splat → BEV → task",note:z("三项结构目标：图像平移等变、相机排列不变、ego 等距变换等变。","Three structural goals: image-translation equivariance, camera-permutation invariance and ego-isometry equivariance."),evidence:"PAPER"},
  {kicker:z("先约定，再计算","Name every frame first"),title:z("坐标系账本","Frame ledger"),line:z("camera、LiDAR、ego、global、网络图像、特征网格和 BEV 都有不同的原点、轴、单位。混淆任意两个都会造成看似合理的镜像结果。","Camera, LiDAR, ego, global, network-image, feature-grid and BEV frames have different origins, axes and units. Mixing any two can produce a plausible-looking mirror."),formula:"pᵇ = Tₐ→ᵦ · pᵃ",note:z("本站统一使用列向量；ego +x 向前、+y 向左、+z 向上。","This lab uses column vectors; ego +x is forward, +y left and +z up."),evidence:"REAL SAMPLE"},
  {kicker:z("标定数据从哪里来","Calibration provenance"),title:z("矩阵如何产生","Where matrices come from"),line:z("nuScenes 用 calibrated_sensor 描述传感器相对车体的旋转和平移，用 ego_pose 描述车体相对 global 的姿态。四元数先归一化并转换成旋转矩阵，再与平移组成 4×4 齐次矩阵。","nuScenes stores sensor-to-body calibration separately from the ego pose in global coordinates. A normalized quaternion becomes a rotation matrix, then joins translation in a 4×4 homogeneous transform."),formula:"T = [[R(q), t], [0,0,0,1]]",note:z("矩阵不是网络学出的参数；它来自这台车在这个传感器时刻的标定与姿态。","These matrices are calibration and pose measurements, not learned network parameters."),evidence:"REAL SAMPLE"},
  {kicker:z("顺序就是语义","Order carries meaning"),title:z("如何组合变换","How transforms compose"),line:z("从 A 经 B 到 C 时，最先作用的矩阵写在最右侧。刚体逆变换不是逐元素取倒数，而是 Rᵀ 与 −Rᵀt。","From A through B to C, the first transform applied sits on the right. A rigid inverse is Rᵀ with −Rᵀt, never an element-wise reciprocal."),formula:"Tₐ→ᴄ = Tʙ→ᴄ Tₐ→ʙ ·  T⁻¹ = [[Rᵀ,−Rᵀt],[0,1]]",note:z("切换矩阵边查看真实数值、逆矩阵以及 T⁻¹T 的残差。","Inspect an edge to see its values, inverse and the residual of T⁻¹T."),evidence:"REAL SAMPLE"},
  {kicker:z("先撤销图像处理","Undo the image pipeline"),title:z("图像预处理坐标","Image preprocessing"),line:z("原始 1600×900 图像先按 0.22 缩放为 352×198，再裁成 352×128。post_rot/post_trans 记录原图到网络图的仿射变换，反投影前必须使用它的逆。","The 1600×900 image is resized to 352×198 and cropped to 352×128. post_rot/post_trans record raw-to-network geometry and must be inverted before unprojection."),formula:"u′ = A u + a  ⇒  u = A⁻¹(u′−a)",note:z("这里显示的不是抽象示例，而是固定帧真实验证预处理。","The numbers shown are the actual validation preprocessing for the pinned frame."),evidence:"REAL SAMPLE"},
  {kicker:z("二维像素只定义一条射线","A pixel defines a ray"),title:z("从像素到射线","Pixel to ray"),line:z("K 把相机米制坐标投影到原图像素；K⁻¹ 只能恢复方向。相机 +x 向右、+y 向下、+z 沿光轴向前，深度 d 就是 zcam。","K projects metric camera coordinates into raw pixels; K⁻¹ recovers only direction. Camera +x is right, +y down and +z optical forward; depth d equals zcam."),formula:"p_cam(d)=K⁻¹[d·u,d·v,d]ᵀ",note:z("同一像素上 4–44 米的 41 个点都会重新投影回同一位置。","All 41 points from 4–44 m reproject to the same pixel."),evidence:"REAL SAMPLE"},
  {kicker:z("像素与特征必须真的对应","Exact sampling anchors"),title:z("特征网格对应关系","Feature-grid correspondence"),line:z("8×22 并非简单按 16 像素整除。官方 frustum 使用 linspace 覆盖 0…351 与 0…127；点击会吸附到最近 anchor，并读取那个格子的真实张量。","The 8×22 grid is not a naïve 16-pixel tiling. Official frustum anchors use linspace over 0…351 and 0…127; clicks snap to the nearest anchor and index that exact tensor cell."),formula:"wⱼ=351·j/21 · hᵢ=127·i/7",note:z("v1 固定读取 [4,11]；v2 已改为所点即所算。","v1 always read [4,11]; v2 makes the selected anchor the actual tensor index."),evidence:"CHECKPOINT"},
  {kicker:z("把深度保留为潜变量","Depth stays latent"),title:z("Lift","Lift"),line:z("每个真实特征格输出 41 个深度 logit 与 64 维 context。softmax 得到 α(d)，外积把同一个 context 按概率分配到整条视锥。","Each real feature cell emits 41 depth logits and a 64D context. Softmax produces α(d), whose outer product distributes context along the frustum."),formula:"f[d,c] = softmax(ℓ)[d] · context[c]",note:z("α 没有直接深度真值监督；它是由最终 BEV 任务塑造的任务型潜变量。","α has no direct depth supervision; the final BEV task shapes this latent allocation."),evidence:"CHECKPOINT"},
  {kicker:z("逐项复现官方 get_geometry","One sample, official order"),title:z("精确的 get_geometry","Exact get_geometry"),line:z("同一个 anchor 和 depth 依次撤销 post transform、构造 [du,dv,d]、乘 K⁻¹、乘 cam2ego 的 R、再加 t。每个中间量都可验算。","The same anchor and depth undo post-transform, form [du,dv,d], multiply K⁻¹, rotate with cam2ego R and finally add t. Every intermediate is auditable."),formula:"pₑ = R K⁻¹[d·A⁻¹(u′), d]ᵀ + t",note:z("符号、实际数字、合并矩阵和官方代码四个页签指向同一采样点。","Symbolic, numeric, composed and source-code tabs refer to one identical sample."),evidence:"REAL SAMPLE"},
  {kicker:z("六个相机，一个 ego","A shared metric frame"),title:z("六相机进入 ego","Six cameras into ego"),line:z("每个相机用自己的 K、R、t 独立 Lift 和变换。落入同一 ego 位置的证据最终相加，因此交换相机及其标定的顺序不会改变结果。","Every camera lifts and transforms with its own K, R and t. Evidence landing at one ego location is summed, so permuting cameras together with calibration changes nothing."),formula:"BEV = Σₙ Splat(Tₙ · Lift(Iₙ))",note:z("视锥光轴直接取 cam2ego 旋转矩阵第三列，全部从车体向外。","Each optical axis is the third cam2ego rotation column, so every frustum points outward."),evidence:"REAL SAMPLE"},
  {kicker:z("离散化、排序、精确求和","Pack · rank · sum"),title:z("Splat 与 QuickCumsum","Splat and QuickCumsum"),line:z("43,296 个候选点按半开边界过滤，量化为 pillar，编码 rank 后排序。前缀和只保留每组末尾，再做相邻组差得到精确 sum pooling。","43,296 candidate points are filtered by half-open bounds, quantized into pillars, ranked and sorted. Prefix sums retain group ends; adjacent differences recover exact sum pooling."),formula:"rank=x(YZB)+y(ZB)+zB+b",note:z("sum 既累积多相机证据，也自然保证相机排列不变。","Sum pooling accumulates multi-camera evidence and is naturally permutation invariant."),evidence:"PAPER"},
  {kicker:z("几何结束，卷积开始","Geometry hands off to CNNs"),title:z("BEV 张量与编码器","BEV tensor and encoder"),line:z("聚合结果写入 [B,C,Z,X,Y]，z 拼入通道得到 [B,64,200,200]。ResNet-18 风格编码器再进行规则二维密集推理。","Aggregates populate [B,C,Z,X,Y], then z collapses into channels to form [B,64,200,200]. A ResNet-18-style encoder performs regular dense 2D reasoning."),formula:"[1,6,41,8,22,64] → [1,64,200,200] → [1,1,200,200]",note:z("tensor 行是 ego x、列是 ego y；显示上方为 +x、左侧为 +y。","Tensor rows are ego x and columns ego y; display up is +x and left is +y."),evidence:"CHECKPOINT"},
  {kicker:z("同一真实点，三个视图","Linked evidence"),title:z("真实样本核验实验室","Real-sample truth lab"),line:z("同一批 34,688 个 LiDAR 点在相机、3D 和 BEV 中同步投影，并与 checkpoint 概率、GT 车辆框和误差区域叠加。","The same 34,688 LiDAR points are synchronized across camera, 3D and BEV views, alongside checkpoint probability, GT vehicle boxes and error regions."),formula:"LiDAR ↔ camera ↔ ego ↔ BEV",note:z("LiDAR 只用于核验空间关系，绝不是这次 LSS 相机推理的输入。","LiDAR is a spatial reference only—it is never an input to this LSS camera inference."),evidence:"REAL SAMPLE"},
  {kicker:z("任务监督塑造潜在几何","What the loss teaches"),title:z("训练、结果与鲁棒性","Training, results and robustness"),line:z("车辆/地图 BCE 只监督最终 BEV。论文结果、camera dropout、标定噪声和新阵列实验是数据集级证据；本站开关只展示固定单帧变化。","Vehicle/map BCE supervises only final BEV. Paper results, camera dropout, calibration noise and new-rig experiments are dataset evidence; site toggles show one fixed frame."),formula:"L = BCEWithLogits(ŷBEV,yBEV)",note:z("14.3M 与 Titan V 35 Hz 是论文报告，不是浏览器性能。","14.3M parameters and 35 Hz on Titan V are paper reports, not browser benchmarks."),evidence:"PAPER"},
  {kicker:z("从空间表征到轨迹决策","From representation to planning"),title:z("Shoot 与局限","Shoot and limitations"),line:z("轨迹模板穿过预测 cost map，沿途代价之和经 Boltzmann softmax 变成概率。官方未发布规划 checkpoint，因此交互仅忠实重建论文方程。","Trajectory templates traverse a predicted cost map; summed cost becomes probability through Boltzmann softmax. No planning checkpoint was released, so the interaction reconstructs only the paper equation."),formula:"p(τ|o) ∝ exp(−Σ₍ₓ,ᵧ₎∈τ cₒ(x,y)/T)",note:z("最后回看单帧、远距离、遮挡、夜间和标定误差，并严格区分论文、真实与教学证据。","Close with single-frame, range, occlusion, night and calibration limits while keeping paper, real and teaching evidence distinct."),evidence:"TEACHING"},
];

export function tx(locale:Locale,value:Localized){return value[locale]}
