export type Mat3 = [[number, number, number], [number, number, number], [number, number, number]];
export type Vec3 = [number, number, number];
export function softmax(values: number[]): number[];
export function mat3Multiply(a: Mat3, b: Mat3): Mat3;
export function mat3Vector(a: Mat3, value: Vec3): Vec3;
export function mat4Multiply(a: number[][], b: number[][]): number[][];
export function mat4Vector(matrix: number[][], point: number[]): number[];
export function rigidToMat4(rotation: Mat3, translation: Vec3): number[][];
export function invertRigidMat4(matrix: number[][]): number[][];
export function quaternionToRotation(quaternion: [number,number,number,number]): Mat3;
export function determinantMat3(matrix: Mat3): number;
export function invertMat3(m: Mat3): Mat3;
export function undoPostTransform(pixel: Vec3, postRotation: Mat3, postTranslation: Vec3): Vec3;
export function pixelToCamera(pixel: Vec3, depth: number, intrinsic: Mat3): Vec3;
export function applyRigid(point: Vec3, rotation: Mat3, translation: Vec3): Vec3;
export function cameraPointToEgo(pixel: [number, number], depth: number, intrinsic: Mat3, rotation: Mat3, translation: Vec3, postRotation?: Mat3, postTranslation?: Vec3): Vec3;
export function projectCameraPoint(point: Vec3, intrinsic: Mat3): [number,number,number] | null;
export function projectLidarPoint(point: number[], lidarToCamera: number[][], intrinsic: Mat3): {camera: number[]; image:number[]} | null;
export function linspace(start:number,end:number,count:number):number[];
export function nearestFeatureAnchor(pixel:[number,number],width?:number,height?:number,featureWidth?:number,featureHeight?:number):{index:[number,number];anchor:[number,number];delta:[number,number]};
export function egoToBevIndex(point:number[],bounds?:number[][]):number[]|null;
export function bevIndexToEgo(index:number[],bounds?:number[][]):number[];
export function egoToScreen(point:number[],bounds?:number[][]):number[]|null;
export function screenToBevIndex(screen:number[],gridSize?:number):number[];
export function binaryStats(probabilities:number[],groundTruth:number[],threshold?:number):{truePositive:number;falsePositive:number;falseNegative:number;trueNegative:number;iou:number};
export function outerProduct(depthProbability: number[], context: number[]): number[][];
export function voxelIndex(point: Vec3, bounds: [Vec3, Vec3, Vec3]): Vec3 | null;
export function voxelRank(index: Vec3, gridShape: Vec3, batch?: number, batchSize?: number): number;
export function quickCumsum(features: number[][], ranks: number[]): {values:number[][];ranks:number[]};
export function naiveSumPool(features: number[][], ranks: number[]): {values:number[][];ranks:number[]};
export function poolCameraContributions(cameraFeatures: number[][]): number[];
export function transformPointSet(points: Vec3[], rotation: Mat3, translation: Vec3): Vec3[];
export function trajectoryCost(points: [number, number][], costMap: (point:[number,number])=>number, comfortWeight?: number): number;
export function boltzmannProbabilities(costs: number[], temperature?: number): number[];
